import AdminLayout from '@/Layouts/AdminLayout';
import AcademyTab from '@/Pages/Settings/Tabs/AcademyTab';
import AiTab from '@/Pages/Settings/Tabs/AiTab';
import AppTab from '@/Pages/Settings/Tabs/AppTab';
import RolesTab from '@/Pages/Settings/Tabs/RolesTab';
import UsersTab from '@/Pages/Settings/Tabs/UsersTab';
import { Head, router, usePage } from '@inertiajs/react';

const TEXT = {
    it: {
        pageTitle: 'Impostazioni',
        tabUsers: 'Utenti',
        tabRoles: 'Ruoli',
        tabApp: 'Impostazioni app',
        tabAi: 'IA',
        tabAcademy: 'Impostazioni accademia',
        academyTabGeneral: 'Impostazioni generali',
        academyTabHalls: 'Sale didattiche',
        academyTabLessons: 'Lezioni',
        academyGeneralPlaceholder: 'Sezione in preparazione.',
        academyHallsTitle: 'Sale didattiche',
        academyHallsDescription: 'Crea gruppi sale (sedi) e gestisci le sale interne.',
        addHallGroup: 'Aggiungi gruppo sale',
        editHallGroup: 'Modifica gruppo sale',
        academyHallGroupsEmpty: 'Nessun gruppo sale.',
        addHall: 'Aggiungi sala',
        editHall: 'Modifica sala',
        academyHallsEmpty: 'Nessuna sala in questo gruppo.',
        academyGroupAddress: 'Indirizzo',
        academyHallType: 'Tipo sala',
        academyHallCapacity: 'Capienza',
        aiSubtitle: 'Collega un provider e attiva un solo modello alla volta.',
        aiApiKey: 'Chiave API',
        aiSaveKey: 'Salva chiave',
        aiCheck: 'Verifica connessione',
        aiActivate: 'Attiva',
        aiDeactivate: 'Disattiva tutto',
        aiActiveModel: 'Modello attivo',
        aiModelSelect: 'Modelli disponibili',
        aiNoModels: 'Nessun modello caricato',
        aiNotConnected: 'Non connesso',
        aiConnected: 'Connesso',
        aiActive: 'Attivo',
        aiError: 'Errore',
        aiSavedMask: 'Chiave salvata',
        usersTitle: 'Utenti',
        usersDescription: 'Account del personale web e account actor collegati ai profili.',
        addUser: 'Aggiungi utente',
        colName: 'Nome',
        colEmail: 'Email',
        colAccountType: 'Tipo account',
        colRole: 'Ruolo web',
        colActive: 'Stato',
        colLinkedProfile: 'Profilo collegato',
        colCreated: 'Creato',
        colActions: 'Azioni',
        empty: 'Nessun utente.',
        modalTitle: 'Crea utente staff',
        editModalTitle: 'Modifica utente',
        fieldName: 'Nome completo',
        fieldEmail: 'Email',
        fieldPassword: 'Password',
        fieldPasswordConfirm: 'Conferma password',
        fieldRole: 'Ruolo web',
        fieldRoleNone: 'Nessun ruolo web',
        fieldAccountType: 'Tipo account',
        fieldIsActive: 'Account attivo',
        fieldCanDelete: 'Permesso di eliminazione dati',
        fieldCanWrite: 'Permesso di creazione e modifica dati',
        accountType_staff: 'Staff',
        accountType_student: 'Studente',
        accountType_parent: 'Genitore',
        accountType_teacher: 'Insegnante',
        linkedNone: 'Nessuno',
        active: 'Attivo',
        inactive: 'Disattivato',
        noDeletePermission: 'Non hai il permesso di eliminare dati.',
        cancel: 'Annulla',
        save: 'Crea utente',
        update: 'Salva modifiche',
        edit: 'Modifica',
        deleting: 'Eliminazione...',
        deleteUser: 'Elimina utente',
        deleteConfirmTitle: 'Conferma eliminazione',
        deleteConfirmHint: 'Digita DELETE per confermare la rimozione dell\'account.',
        deleteConfirmLabel: 'Conferma',
        deleteConfirmPlaceholder: 'DELETE',
        cannotDeleteSelf: 'Non puoi eliminare il tuo account da qui.',
        createRoleTitle: 'Crea ruolo',
        addRole: 'Aggiungi ruolo',
        existingRolesTitle: 'Ruoli esistenti',
        saveRole: 'Salva ruolo',
        colSlug: 'Slug',
        colAdmin: 'Admin',
        colActive: 'Attivo',
        colUsers: 'Utenti',
        colMenuItems: 'Voci menu',
        yes: 'Sì',
        no: 'No',
        editRoleTitle: 'Modifica ruolo',
        deleteConfirm: 'Eliminare questo ruolo?',
        delete: 'Elimina',
        saveChanges: 'Salva modifiche',
        fieldSlug: 'Slug',
        fieldDescription: 'Descrizione',
        fullAdministrator: 'Amministratore completo (tutte le voci menu)',
        active: 'Attivo',
        allowedMenuItems: 'Voci menu consentite',
        appTitle: 'Impostazioni app',
        appBody: 'Questa è una pagina segnaposto per le impostazioni dell\'applicazione.',
    },
    en: {
        pageTitle: 'Settings',
        tabUsers: 'Users',
        tabRoles: 'Roles',
        tabApp: 'App settings',
        tabAi: 'AI',
        tabAcademy: 'Academy settings',
        academyTabGeneral: 'General settings',
        academyTabHalls: 'Study halls',
        academyTabLessons: 'Lessons',
        academyGeneralPlaceholder: 'Section coming soon.',
        academyHallsTitle: 'Study halls',
        academyHallsDescription: 'Create hall groups (locations) and manage halls inside.',
        addHallGroup: 'Add hall group',
        editHallGroup: 'Edit hall group',
        academyHallGroupsEmpty: 'No hall groups yet.',
        addHall: 'Add hall',
        editHall: 'Edit hall',
        academyHallsEmpty: 'No halls in this group.',
        academyGroupAddress: 'Address',
        academyHallType: 'Hall type',
        academyHallCapacity: 'Capacity',
        aiSubtitle: 'Connect one provider and activate one model at a time.',
        aiApiKey: 'API key',
        aiSaveKey: 'Save key',
        aiCheck: 'Check connection',
        aiActivate: 'Activate',
        aiDeactivate: 'Deactivate all',
        aiActiveModel: 'Active model',
        aiModelSelect: 'Available models',
        aiNoModels: 'No models loaded yet',
        aiNotConnected: 'Not connected',
        aiConnected: 'Connected',
        aiActive: 'Active',
        aiError: 'Error',
        aiSavedMask: 'Saved key',
        usersTitle: 'Users',
        usersDescription: 'Staff web accounts and actor accounts linked to profiles.',
        addUser: 'Add user',
        colName: 'Name',
        colEmail: 'Email',
        colAccountType: 'Account type',
        colRole: 'Web role',
        colLinkedProfile: 'Linked profile',
        colCreated: 'Created',
        colActions: 'Actions',
        empty: 'No users yet.',
        modalTitle: 'Create staff user',
        editModalTitle: 'Edit user',
        fieldName: 'Full name',
        fieldEmail: 'Email',
        fieldPassword: 'Password',
        fieldPasswordConfirm: 'Confirm password',
        fieldRole: 'Web role',
        fieldRoleNone: 'No web role',
        fieldAccountType: 'Account type',
        fieldIsActive: 'Account active',
        fieldCanDelete: 'Permission to delete data',
        fieldCanWrite: 'Permission to create and modify data',
        accountType_staff: 'Staff',
        accountType_student: 'Student',
        accountType_parent: 'Parent',
        accountType_teacher: 'Teacher',
        linkedNone: 'None',
        inactive: 'Disabled',
        noDeletePermission: 'You do not have permission to delete data.',
        cancel: 'Cancel',
        save: 'Create user',
        update: 'Save changes',
        edit: 'Edit',
        deleting: 'Deleting...',
        deleteUser: 'Delete user',
        deleteConfirmTitle: 'Confirm deletion',
        deleteConfirmHint: 'Type DELETE to confirm account removal.',
        deleteConfirmLabel: 'Confirmation',
        deleteConfirmPlaceholder: 'DELETE',
        cannotDeleteSelf: 'You cannot delete your own account here.',
        createRoleTitle: 'Create role',
        addRole: 'Add role',
        existingRolesTitle: 'Existing roles',
        saveRole: 'Save role',
        colSlug: 'Slug',
        colAdmin: 'Admin',
        colActive: 'Active',
        colUsers: 'Users',
        colMenuItems: 'Menu items',
        yes: 'Yes',
        no: 'No',
        editRoleTitle: 'Edit role',
        deleteConfirm: 'Delete this role?',
        delete: 'Delete',
        saveChanges: 'Save changes',
        fieldSlug: 'Slug',
        fieldDescription: 'Description',
        fullAdministrator: 'Full administrator (all menu items)',
        active: 'Active',
        allowedMenuItems: 'Allowed menu items',
        appTitle: 'App settings',
        appBody: 'This is a placeholder app settings page.',
    },
    ru: {
        pageTitle: 'Настройки',
        tabUsers: 'Пользователи',
        tabRoles: 'Роли',
        tabApp: 'Настройки приложения',
        tabAi: 'ИИ',
        tabAcademy: 'Настройки академии',
        academyTabGeneral: 'Общие настройки',
        academyTabHalls: 'Учебные залы',
        academyTabLessons: 'Уроки',
        academyGeneralPlaceholder: 'Раздел в разработке.',
        academyHallsTitle: 'Учебные залы',
        academyHallsDescription: 'Создавайте группы залов (локации) и управляйте залами внутри.',
        addHallGroup: 'Добавить группу залов',
        editHallGroup: 'Изменить группу залов',
        academyHallGroupsEmpty: 'Групп залов пока нет.',
        addHall: 'Добавить зал',
        editHall: 'Изменить зал',
        academyHallsEmpty: 'В этой группе пока нет залов.',
        academyGroupAddress: 'Адрес',
        academyHallType: 'Тип зала',
        academyHallCapacity: 'Вместимость',
        aiSubtitle: 'Подключите одного провайдера и активируйте только одну модель одновременно.',
        aiApiKey: 'API key',
        aiSaveKey: 'Сохранить ключ',
        aiCheck: 'Проверить',
        aiActivate: 'Активировать',
        aiDeactivate: 'Деактивировать все',
        aiActiveModel: 'Активная модель',
        aiModelSelect: 'Доступные модели',
        aiNoModels: 'Модели еще не загружены',
        aiNotConnected: 'Not connected',
        aiConnected: 'Connected',
        aiActive: 'Active',
        aiError: 'Error',
        aiSavedMask: 'Сохраненный ключ',
        usersTitle: 'Пользователи',
        usersDescription: 'Веб-аккаунты персонала и actor-аккаунты, связанные с профилями.',
        addUser: 'Добавить пользователя',
        colName: 'Имя',
        colEmail: 'Email',
        colAccountType: 'Тип аккаунта',
        colRole: 'Веб-роль',
        colLinkedProfile: 'Связанный профиль',
        colCreated: 'Создан',
        colActions: 'Действия',
        empty: 'Пользователей пока нет.',
        modalTitle: 'Создать пользователя staff',
        editModalTitle: 'Редактировать пользователя',
        fieldName: 'Полное имя',
        fieldEmail: 'Email',
        fieldPassword: 'Пароль',
        fieldPasswordConfirm: 'Подтверждение пароля',
        fieldRole: 'Веб-роль',
        fieldRoleNone: 'Без веб-роли',
        fieldAccountType: 'Тип аккаунта',
        fieldIsActive: 'Аккаунт активен',
        fieldCanDelete: 'Разрешение на удаление данных',
        fieldCanWrite: 'Разрешение на создание и изменение данных',
        accountType_staff: 'Staff',
        accountType_student: 'Студент',
        accountType_parent: 'Родитель',
        accountType_teacher: 'Преподаватель',
        linkedNone: 'Нет',
        inactive: 'Отключён',
        noDeletePermission: 'У вас нет разрешения на удаление данных.',
        cancel: 'Отмена',
        save: 'Создать пользователя',
        update: 'Сохранить изменения',
        edit: 'Изменить',
        deleting: 'Удаляем...',
        deleteUser: 'Удалить пользователя',
        deleteConfirmTitle: 'Подтверждение удаления',
        deleteConfirmHint: 'Введите DELETE для подтверждения удаления аккаунта.',
        deleteConfirmLabel: 'Подтверждение',
        deleteConfirmPlaceholder: 'DELETE',
        cannotDeleteSelf: 'Нельзя удалить собственный аккаунт из этого окна.',
        createRoleTitle: 'Создать роль',
        addRole: 'Добавить роль',
        existingRolesTitle: 'Существующие роли',
        saveRole: 'Сохранить роль',
        colSlug: 'Slug',
        colAdmin: 'Админ',
        colActive: 'Активна',
        colUsers: 'Пользователи',
        colMenuItems: 'Пункты меню',
        yes: 'Да',
        no: 'Нет',
        editRoleTitle: 'Редактировать роль',
        deleteConfirm: 'Удалить эту роль?',
        delete: 'Удалить',
        saveChanges: 'Сохранить изменения',
        fieldSlug: 'Slug',
        fieldDescription: 'Описание',
        fullAdministrator: 'Полный администратор (все пункты меню)',
        active: 'Активна',
        allowedMenuItems: 'Разрешённые пункты меню',
        appTitle: 'Настройки приложения',
        appBody: 'Это заглушка страницы настроек приложения.',
    },
    uk: {
        pageTitle: 'Налаштування',
        tabUsers: 'Користувачі',
        tabRoles: 'Ролі',
        tabApp: 'Налаштування застосунку',
        tabAi: 'ШІ',
        tabAcademy: 'Налаштування академії',
        academyTabGeneral: 'Загальні налаштування',
        academyTabHalls: 'Навчальні зали',
        academyTabLessons: 'Уроки',
        academyGeneralPlaceholder: 'Розділ у розробці.',
        academyHallsTitle: 'Навчальні зали',
        academyHallsDescription: 'Створюйте групи залів (локації) та керуйте залами всередині.',
        addHallGroup: 'Додати групу залів',
        editHallGroup: 'Редагувати групу залів',
        academyHallGroupsEmpty: 'Груп залів поки немає.',
        addHall: 'Додати зал',
        editHall: 'Редагувати зал',
        academyHallsEmpty: 'У цій групі поки немає залів.',
        academyGroupAddress: 'Адреса',
        academyHallType: 'Тип залу',
        academyHallCapacity: 'Місткість',
        aiSubtitle: 'Підключіть одного провайдера і активуйте лише одну модель одночасно.',
        aiApiKey: 'API key',
        aiSaveKey: 'Зберегти ключ',
        aiCheck: 'Перевірити',
        aiActivate: 'Активувати',
        aiDeactivate: 'Деактивувати все',
        aiActiveModel: 'Активна модель',
        aiModelSelect: 'Доступні моделі',
        aiNoModels: 'Моделі ще не завантажені',
        aiNotConnected: 'Not connected',
        aiConnected: 'Connected',
        aiActive: 'Active',
        aiError: 'Error',
        aiSavedMask: 'Збережений ключ',
        usersTitle: 'Користувачі',
        usersDescription: 'Веб-акаунти персоналу та actor-акаунти, пов’язані з профілями.',
        addUser: 'Додати користувача',
        colName: "Ім'я",
        colEmail: 'Email',
        colAccountType: 'Тип акаунта',
        colRole: 'Веб-роль',
        colLinkedProfile: 'Пов’язаний профіль',
        colCreated: 'Створено',
        colActions: 'Дії',
        empty: 'Користувачів поки що немає.',
        modalTitle: 'Створити користувача staff',
        editModalTitle: 'Редагувати користувача',
        fieldName: "Повне ім'я",
        fieldEmail: 'Email',
        fieldPassword: 'Пароль',
        fieldPasswordConfirm: 'Підтвердження пароля',
        fieldRole: 'Веб-роль',
        fieldRoleNone: 'Без веб-ролі',
        fieldAccountType: 'Тип акаунта',
        fieldIsActive: 'Акаунт активний',
        fieldCanDelete: 'Дозвіл на видалення даних',
        fieldCanWrite: 'Дозвіл на створення та зміну даних',
        accountType_staff: 'Staff',
        accountType_student: 'Студент',
        accountType_parent: 'Батько/мати',
        accountType_teacher: 'Викладач',
        linkedNone: 'Немає',
        inactive: 'Вимкнений',
        noDeletePermission: 'У вас немає дозволу на видалення даних.',
        cancel: 'Скасувати',
        save: 'Створити користувача',
        update: 'Зберегти зміни',
        edit: 'Редагувати',
        deleting: 'Видаляємо...',
        deleteUser: 'Видалити користувача',
        deleteConfirmTitle: 'Підтвердження видалення',
        deleteConfirmHint: 'Введіть DELETE для підтвердження видалення акаунта.',
        deleteConfirmLabel: 'Підтвердження',
        deleteConfirmPlaceholder: 'DELETE',
        cannotDeleteSelf: 'Не можна видалити власний акаунт з цього вікна.',
        createRoleTitle: 'Створити роль',
        addRole: 'Додати роль',
        existingRolesTitle: 'Існуючі ролі',
        saveRole: 'Зберегти роль',
        colSlug: 'Slug',
        colAdmin: 'Адмін',
        colActive: 'Активна',
        colUsers: 'Користувачі',
        colMenuItems: 'Пункти меню',
        yes: 'Так',
        no: 'Ні',
        editRoleTitle: 'Редагувати роль',
        deleteConfirm: 'Видалити цю роль?',
        delete: 'Видалити',
        saveChanges: 'Зберегти зміни',
        fieldSlug: 'Slug',
        fieldDescription: 'Опис',
        fullAdministrator: 'Повний адміністратор (усі пункти меню)',
        active: 'Активна',
        allowedMenuItems: 'Дозволені пункти меню',
        appTitle: 'Налаштування застосунку',
        appBody: 'Це заглушка сторінки налаштувань застосунку.',
    },
};

const TABS = ['users', 'roles', 'app', 'academy', 'ai'];

export default function SettingsIndex({
    tab = 'users',
    academyTab = 'halls',
    lessonTab = 'ballet',
    users = [],
    roleOptions = [],
    managedRoles = [],
    menuRegistry = [],
    academyBuildings = [],
    aiProviders = [],
    lessons = [],
    lessonTeachers = [],
}) {
    const { locale = 'it' } = usePage().props;
    const t = TEXT[locale] ?? TEXT.it;
    const activeTab = TABS.includes(tab) ? tab : 'users';

    const switchTab = (nextTab) => {
        if (nextTab === activeTab) {
            return;
        }

        router.get(route('settings.index'), { tab: nextTab }, {
            preserveState: true,
            preserveScroll: true,
            replace: true,
        });
    };

    const tabLabels = {
        users: t.tabUsers,
        roles: t.tabRoles,
        app: t.tabApp,
        academy: t.tabAcademy,
        ai: t.tabAi,
    };

    return (
        <AdminLayout title={t.pageTitle}>
            <Head title={t.pageTitle} />

            <div className="space-y-6">
                <div className="border-b border-slate-200">
                    <nav className="-mb-px flex flex-wrap gap-1">
                        {TABS.map((tabId) => (
                            <button
                                key={tabId}
                                type="button"
                                onClick={() => switchTab(tabId)}
                                className={`border-b-2 px-4 py-2.5 text-sm font-medium transition ${
                                    activeTab === tabId
                                        ? 'border-indigo-600 text-indigo-600'
                                        : 'border-transparent text-slate-600 hover:border-slate-300 hover:text-slate-900'
                                }`}
                            >
                                {tabLabels[tabId]}
                            </button>
                        ))}
                    </nav>
                </div>

                {activeTab === 'users' && (
                    <UsersTab t={t} users={users} roleOptions={roleOptions} />
                )}
                {activeTab === 'roles' && (
                    <RolesTab t={t} managedRoles={managedRoles} menuRegistry={menuRegistry} />
                )}
                {activeTab === 'app' && (
                    <AppTab t={t} />
                )}
                {activeTab === 'academy' && (
                    <AcademyTab
                        t={t}
                        buildings={academyBuildings}
                        academyTab={academyTab}
                        lessonTab={lessonTab}
                        lessons={lessons}
                        lessonTeachers={lessonTeachers}
                    />
                )}
                {activeTab === 'ai' && (
                    <AiTab t={t} providers={aiProviders} />
                )}
            </div>
        </AdminLayout>
    );
}
